FROM ubuntu

WORKDIR /sccode

# --- update system
RUN \
  apt-get -qq update && \
  apt-get -y upgrade && \
  apt-get install -y nano wget git build-essential libjack-jackd2-dev libsndfile1-dev libasound2-dev libavahi-client-dev libicu-dev libreadline6-dev libfftw3-dev libxt-dev pkg-config cmake subversion && \
  rm -rf /var/lib/apt/lists/*

WORKDIR sc-build

# --- build supercollider from source
RUN git clone --recursive https://github.com/supercollider/supercollider.git

WORKDIR supercollider

RUN \
  git checkout develop && \
  mkdir build && \
  cd build && \
  cmake -L -DCMAKE_BUILD_TYPE="Release" -DBUILD_TESTING=OFF -DENABLE_TESTSUITE=OFF -DSUPERNOVA=OFF -DNATIVE=ON -DSC_EL=OFF -DSC_VIM=OFF -DSC_QT=OFF -DSC_HIDAPI=OFF -DSC_IDE=OFF -DSC_ED=OFF .. && \
  make && \
  make install

# --- remove and add relevant directories
RUN mv /usr/local/share/SuperCollider/SCClassLibrary/Common/GUI /usr/local/share/SuperCollider/SCClassLibrary/scide_scqt/GUI
RUN mv /usr/local/share/SuperCollider/SCClassLibrary/JITLib/GUI /usr/local/share/SuperCollider/SCClassLibrary/scide_scqt/JITLibGUI
RUN mkdir /usr/local/share/SuperCollider/Extensions
RUN mkdir /root/.local/share/SuperCollider/Extensions

# --- ports
EXPOSE 57110 UDP
EXPOSE 57120 UDP